---

#- name: 'ensure http check is installed'
#  package:
#    name: nagios-plugins-http
#    state: present

- name: 'check all port numbers are accessible from current host'
  wait_for:
    host: localhost
    port: '{{item}}'
    delay: 1               # No wait before first check (sec)
    timeout: 10            # Stop checking after timeout (sec)
  ignore_errors: yes
  loop:
    '{{wait_for_ports}}'
  retries: 10
  delay: 10
  when: wait_for_ports is defined and wait_for_ports|length > 0

- name: 'check IOR for CMS'
  uri:
    url: 'http://{{ansible_fqdn}}:40180/coremedia/ior'
    return_content: yes
  ignore_errors: yes
  register: check_ior_cms
  when: ior_cms is defined and ior_cms == True

- name: 'check IOR for MLS'
  uri:
    url: 'http://{{ansible_fqdn}}:40280/coremedia/ior'
    return_content: yes
  ignore_errors: yes
  register: check_ior_mls
  when: ior_mls is defined and ior_mls == True

- name: 'check IOR for WFS'
  uri:
    url: 'http://{{ansible_fqdn}}:40380/workflow/ior'
    return_content: yes
  ignore_errors: yes
  register: check_ior_wfs
  when: ior_wfs is defined and ior_wfs == True

- name: 'check IOR for RLS'
  uri:
    url: 'http://{{ansible_fqdn}}:42080/coremedia/ior'
    return_content: yes
  ignore_errors: yes
  register: check_ior_rls
  when: ior_rls is defined and ior_rls == True

#
#- name: 'check certificate'
#  shell: |
#    /usr/lib64/nagios/plugins/check_http --hostname {{ansible_fqdn}} --ssl --certificate=5
#  register: check_certificate
#
#- name: 'check_http to http://overview.{{ansible_fqdn}}'
#  shell: |
#    /usr/lib64/nagios/plugins/check_http --hostname overview.{{ansible_fqdn}} --string="CoreMedia"
#  register: check_http_overview
#
#- name: 'check_http to https://overview.{{ansible_fqdn}}'
#  shell: |
#    /usr/lib64/nagios/plugins/check_http --hostname overview.{{ansible_fqdn}} --ssl --string="CoreMedia"
#  register: check_https_overview
#
#- name: 'check_http to https://studio.{{ansible_fqdn}}/studio/'
#  shell: |
#    /usr/lib64/nagios/plugins/check_http --hostname studio.{{ansible_fqdn}} --url /studio/ --ssl --string "STYLES FOR THE SPINNER"
#  register: check_https_studio

#- name: 'output - IOR CMS'
#  debug:
#    var: check_ior_cms.msg
#
#- name: 'output - IOR MLS'
#  debug:
#    var: check_ior_mls.msg
#
#- name: 'output - IOR WFS'
#  debug:
#    var: check_ior_wfs.msg
#
#- name: 'output - IOR RLS'
#  debug:
#    var: check_ior_rls.msg
#
#- name: 'output - certificate check'
#  debug:
#    var: check_certificate.stdout
#
#- name: 'output - http overview'
#  debug:
#    var: check_http_overview.stdout
#
#- name: 'output - https overview'
#  debug:
#    var: check_https_overview.stdout
#
#- name: 'output - https studio'
#  debug:
#    var: check_https_studio.stdout
#
