---

- name: prepare system
  ansible.builtin.include_tasks: prepare.yml

- name: download artefacts
  ansible.builtin.include_tasks: download.yml

- name: install tomcat
  ansible.builtin.include_tasks: install.yml

- name: set facts
  ansible.builtin.include_tasks: set_fact.yml

#- name: handle service
#  include_tasks: service.yml
