---

- name: download tomcat binary to local folder
  become: false
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  run_once: true
  delegate_to: localhost
  check_mode: false
  tags:
    - tomcat

- name: propagate tomcat archiv
  copy:
    src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /tmp
  tags:
    - tomcat

- block:

  - name: download jar files
    become: false
    get_url:
      url: "{{ tomcat_artefact_url }}/{{ item.src }}"
      dest: /tmp
      checksum: "sha1:{{ item.checksum }}"
    with_items:
      "{{ tomcat_files }}"
    register: _download_artefact
    until: _download_artefact is succeeded
    retries: 5
    delay: 2
    run_once: true
    delegate_to: localhost
    check_mode: false
    tags:
      - tomcat

  - name: propagate jar files
    copy:
      src: "/tmp/{{ item.src }}"
      dest: /tmp/
    with_items:
      "{{ tomcat_files }}"
    tags:
      - tomcat
  when: tomcat_artefact_url is defined and tomcat_artefact_url != ''

- name: propagate jar files
  copy:
    src: "{{ item.src }}"
    dest: /tmp/
    checksum: "{{ item.checksum }}"
  with_items:
    "{{ tomcat_files }}"
  when: tomcat_artefact_url is not defined or tomcat_artefact_url is defined and tomcat_artefact_url == ''
  tags:
    - tomcat
