---

- name: prepare system
  include_tasks: prepare.yml

- name: download artefacts
  include_tasks: download.yml

- name: install tomcat
  include_tasks: install.yml

- name: set facts
  include_tasks: set_fact.yml

#- name: handle service
#  include_tasks: service.yml
