---

- name: enable tomcat-{{ tomcat_version }} service
  service:
    name: tomcat{{ tomcat_version }}
    enabled: true
  when:
    - tomcat_service.enabled is defined
    - tomcat_service.enabled

- name: "ensure tomcat-{{ tomcat_version }} service are {{ tomcat_service.state }}"
  service:
    name: "tomcat{{ tomcat_version }}.service"
    state: "{{ tomcat_service.state }}"
  when:
    - tomcat_service.state is defined
    - tomcat_service.state in ["started", "stopped"]
