---

- name: make sure ansible local facts directory exists
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: create custom fact file
  template:
    src: tomcat.fact.j2
    dest: /etc/ansible/facts.d/tomcat.fact
    owner: root
    group: root
    mode: 0755

- name: reload local facts
  setup:
